main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.redirect_to_index, name='redirect-to-index'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('model/<slug:slug>/', views.ModelListView.as_view(), name='model'),
    path('review/<slug:slug>/', views.ReviewListView.as_view(), name='review'),
    path('review-detail/<slug:slug>/', views.ReviewView.as_view(), name='review_detail'),
    path('new-phone/', views.AddPhoneView.as_view(), name='new_phone'),
    path('new-review/', views.AddReviewView.as_view(), name='new_review')
]

phoneradar-django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
]

phoneradar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
]

PhoneReview/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Brand(models.Model):
    title = models.CharField(max_length=60)
    origin = models.CharField(max_length=20)
    manufacturing_since = models.IntegerField()
    slug = models.SlugField(max_length=150, default='')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Model(models.Model):
    title = models.CharField(max_length=60)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    launch_date = models.DateField()
    platform = models.CharField(max_length=20)
    news_link = models.TextField(blank=True)
    slug = models.SlugField(max_length=150, default='')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Review(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    model = models.ManyToManyField(Model)
    date = models.DateField()
    slug = models.SlugField(max_length=150, default='')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(Review, self).save(*args, **kwargs)
        model_slugs = list(self.model.all().values_list('slug', flat=True))
        self.slug = '%i-%s' % (self.id, slugify('-'.join(model_slugs)))
        super(Review, self).save(*args, **kwargs)

main/models.py
from django.forms import ModelForm

from PhoneReview.models import Model, Review


# Create your models here.
class PhoneForm(ModelForm):
    class Meta:
        model = Model
        fields = '__all__'
        exclude = ['slug']


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = '__all__'
        exclude = ['slug']

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import generic

from PhoneReview.models import Brand, Model, Review
from main.models import PhoneForm, ReviewForm


# Create your views here.
def redirect_to_index(request):
    return redirect('/index')


class IndexView(generic.ListView):
    model = Brand
    template_name = 'index.html'
    context_object_name = 'all_brands'

    def get_queryset(self):
        return Brand.objects.all()


class ModelListView(generic.ListView):
    model = Model
    template_name = 'model.html'
    context_object_name = 'all_models'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        brand_instance = Brand.objects.get(slug=slug)
        context['brands'] = Brand.objects.all()
        context['brand'] = brand_instance.title
        return context

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        return Model.objects.filter(brand__slug=slug)


class ReviewListView(generic.ListView):
    model = Review
    template_name = 'review-list.html'
    context_object_name = 'all_reviews'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        model_instance = Model.objects.get(slug=slug)
        context['news_link'] = model_instance.news_link
        context['model'] = model_instance.title
        return context

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        return Review.objects.filter(model__slug__contains=slug)


class ReviewView(generic.DetailView):
    model = Review
    template_name = 'review-detail.html'
    context_object_name = 'review'

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        return Review.objects.get(slug=slug)


class AddPhoneView(generic.TemplateView):
    template_name = 'new-phone.html'

    def post(self, request, *args, **kwargs):
        form = PhoneForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:index'))
        else:
            args = {
                'form': form,
                'models': Model.objects.all()
            }
            return render(request, self.template_name, args)

    def get(self, request, *args, **kwargs):
        form = PhoneForm()
        models = Model.objects.all()
        args = {
            'form': form,
            'models': models
        }
        return render(request, self.template_name, args)


class AddReviewView(generic.TemplateView):
    template_name = 'new-review.html'

    def post(self, request, *args, **kwargs):
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:index'))
        else:
            args = {
                'form': form,
                'models': Review.objects.all()
            }
            return render(request, self.template_name, args)

    def get(self, request, *args, **kwargs):
        form = ReviewForm()
        models = Review.objects.all()
        args = {
            'form': form,
            'models': models
        }
        return render(request, self.template_name, args)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- Custom CSS -->
    <style>
        body {
            padding-top: 70px;
        }

        .content {
            text-align: center;
            padding: 20px;
        }

        .vertical-bar {
            display: inline-block;
            content: "";
            width: 1px;
            height: 20px;
            background-color: #000;
            margin-right: 10px;
        }
    </style>
</head>
<body>
<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="nav-logo">
        <img src="{% static '/logo.jpeg' %}" alt="Phone Radar Logo"
             style="width: 50px; height: auto;border-radius: 50%;">
    </div>
    <span class="vertical-bar"></span>
    <a class="navbar-brand" href="/index">Phone Radar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/new-phone">Add New Phone</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/new-review">Add New Review</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Content Section -->
<div class="content">
    {% block content %}{% endblock %}
</div>


{% block script %}{% endblock %}

<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Phone Radar | Brand List{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h2>Brand List</h2>
                <ul class="list-group">
                    {% for brand in all_brands %}
                        <li class="list-group-item"><a href="{% url 'main:model' brand.slug %}">{{ brand.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/model.html
{% extends "base.html" %}
{% load static %}
{% block title %}Phone Radar | Model List - {{ brand }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Brand List</h5>
                        <ul class="list-group">
                            {% for brand in brands %}
                                <li class="list-group-item"><a
                                        href="{% url 'main:model' brand.slug %}">{{ brand.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col">
                <h2>Model List</h2>
                <ul class="list-group">
                    {% for model in all_models %}
                        <li class="list-group-item"><a href="{% url 'main:review' model.slug %}">{{ model.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/new-phone.html
{% extends "base.html" %}
{% load static %}
{% block title %}Phone Radar | Add New Phone{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Existed Model</h5>
                        <ul class="list-group">
                            {% for model in models %}
                                <li class="list-group-item">{{ model.title }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-form-label">
                                    <label for="{{ field.id_for_label }}" class="text-left">{{ field.label }}</label>
                                </div>
                                <div class="col-form-label">
                                    {{ field }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/new-review.html
{% extends "base.html" %}
{% load static %}
{% block title %}Phone Radar | Add New Review{% endblock %}
{% block content %}
<div class="container">
        <div class="row">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-form-label">
                                    <label for="{{ field.id_for_label }}" class="text-left">{{ field.label }}</label>
                                </div>
                                <div class="col-form-label">
                                    {{ field }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/review-detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Phone Radar | {{ review.title }}{% endblock %}
{% block content %}
    <div class="container">
        <h1>{{ review.title }}</h1>
        <p>Publish Date: {{ review.date }}</p>
        <div class="row">
            <div class="col">
                <p class="text-lg-left">{{ review.content | linebreaksbr }}</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/review-list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Phone Radar | Review List - {{ model }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">News Link</h5>
                        <span id="links" style="display: none">{{ news_link }}</span>
                        <ul class="list-group" id="link-list">
                            <!-- Links will be dynamically added here -->
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col">
                <h2 class="title">Review List</h2>
                <ul class="list-group">
                    {% for review in all_reviews %}
                        <li class="list-group-item"><a
                                href="{% url 'main:review_detail' review.slug %}">{{ review.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}


{% block script %}
    <script type="text/javascript">
        const links = document.getElementById("links").innerText;
        const linksArray = links.split("\n");
        const list = document.getElementById("link-list");
        linksArray.forEach(function (link) {
            const listItem = document.createElement("li");
            listItem.className = "list-group-item";
            const linkElement = document.createElement("a");
            linkElement.href = link;
            linkElement.innerText = link;
            listItem.appendChild(linkElement);
            list.appendChild(listItem);
        });
    </script>
{% endblock %}